# Generated by Django 4.2.3 on 2023-08-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_languagetemp'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatLngCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=200)),
                ('lng', models.DecimalField(decimal_places=2, max_digits=10)),
                ('city_ascii', models.CharField(max_length=200)),
            ],
        ),
    ]
